//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Online_Application.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://agileapp.agilebiz.co.ke:10001/schoolsystem/WS/Arthur%20Solutions/Page/Cour" +
            "seList")]
        public string Online_Application_CourseListRef_CourseList_Service {
            get {
                return ((string)(this["Online_Application_CourseListRef_CourseList_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://agileapp.agilebiz.co.ke:10001/schoolsystem/WS/Arthur%20Solutions/Page/Appl" +
            "icantForm")]
        public string Online_Application_ApplicantFormRef_ApplicantForm_Service {
            get {
                return ((string)(this["Online_Application_ApplicantFormRef_ApplicantForm_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://agileapp.agilebiz.co.ke:10001/schoolsystem/WS/Arthur%20Solutions/Page/Appl" +
            "icantList")]
        public string Online_Application_ApplicantListRef_ApplicantList_Service {
            get {
                return ((string)(this["Online_Application_ApplicantListRef_ApplicantList_Service"]));
            }
        }
    }
}
